### ISSUE TITLE
Error when opening the img files (in a 3ds nand backup)

### ISSUE THREAD

**Issue by takeoaol** [ihaveamac/ninfs#102]
When I tried opening "ctrnand_full.img" or "twlnand_full.img" the file explorer in windows said "The disc image file is corrupted." I tried running a nand backup twice in gm9 and once in fbi. I still had the same result.

**Comment by ihaveamac** [comment]
You need a separate program like OSFMount for the FAT16/12 partitions. Windows has no ability to read these on its own.
