### ISSUE TITLE
Suggestion: add support for inputting seed directly

### ISSUE THREAD

**Issue by mariomadproductions** [ihaveamac/ninfs#31]
as a hex number like ctrtool

**Comment by ihaveamac** [comment]
Maybe.

**Comment by mariomadproductions** [comment]
This is a bit off-topic, but is there a way to add a seed to a seeddb.bin without the use of a 3DS?

**Comment by ihaveamac** [comment]
The seeddb format is very simple, you can make your own tool for it. Numbers are little-endian.
```
offset           size

header:
   0x0            0x4   seed count
   0x4            0xC   padding
  0x10   (count*0x20)   entries

entry:
   0x0            0x8   title id
   0x8           0x10   seed
  0x18            0x8   padding
```

**Comment by NWPlayer123** [comment]
+1 on adding this, would make my life easier when making mount scripts

**Comment by ihaveamac** [comment]
Added --seed in https://github.com/ihaveamac/ninfs/commit/43cdcc597fd3eaf06af090b2855252690d4eb295
Not usable in the gui yet.
