### ISSUE TITLE
[Feature Request] Backup *.cia from Nintendo 3DS folder

### ISSUE THREAD

**Issue by TurdPooCharger** [ihaveamac/ninfs#32]
While helping a GBAtemp user transfer his setup from a New 2DS XL to New 3DS XL, he asked if there was a desktop program that can dump his game collection.

[New 2ds xl to new 3ds xl transfer.](https://gbatemp.net/threads/new-2ds-xl-to-new-3ds-xl-transfer.520557/#post-8333863)

I couldn't think of a different program other than GodMode9 that has this capability. Perhaps this an endeavor worth pursuing for fuse-3ds.

**Comment by TurdPooCharger** [comment]
I'm not familiar about other forms of the ticket file other than the one found in CTRNAND. :/

If one were to extract the _ticket.db_ from the 3DS system tied to the **Nintendo 3DS** folder in question (alongside with _movable.sed_ for decryption), would it be possible to dump titles into *.cia?

**Comment by ihaveamac** [comment]
how it would work:
1. Dump tickets from ticket.db (either gm9 or another program)
2. Decrypt SD contents (fuse-3ds, copy from A: in gm9, etc.)
3. Generate CIAs using dumped tickets
