### ISSUE TITLE
Treats some decrypted cart images as encrypted

### ISSUE THREAD

**Issue by TheFearsomeDzeraora** [ihaveamac/ninfs#33]
fuse-3ds treats some of my cart images as encrypted, thus attempting to decrypt what is already decrypted and then failing to mount romfs/exefs. The source images successfully get opened by Citra and a lot of other programs, while trying to open decrypted.cxi with Citra leads to it just crashing.

**Comment by ihaveamac** [comment]
The encryption flag needs to be fixed. Unfortunately older methods to decrypt don't fix this automatically. If I decide to put this in fuse-3ds I would need to figure out the best way.
