### ISSUE TITLE
Taking a long time

### ISSUE THREAD

**Issue by CecilFF4** [ihaveamac/ninfs#34]
Fuse now takes an inordinate amount of time to mount NANDs or SD contents. It used to be about a second or so once the Mount button was pushed. Now it consistently takes 5 minutes (I timed it). I'm assuming the last Win10 update did something to cause this because nothing else of significance changed on my PC.

Fuse 1.3.1 x64
Win 10

**Comment by ihaveamac** [comment]
Where are the executable and source file(NAND/SD dir) located?
