### ISSUE TITLE
Add support for cdn content directories that use "tmd.ver" naming

### ISSUE THREAD

**Issue by mariomadproductions** [ihaveamac/ninfs#36]
On the CDN you get non-current tmds by specifying the tmd version by appending ``.ver`` to ``tmd``, giving you a file like "tmd.1". Fuse-3ds doesn't pick up tmds with this filenaming. Not a big problem but it would be good if this could be fixed.

**Comment by ihaveamac** [comment]
Maybe the cdn mount could accept a tmd file directly, and it reads the contents next to it. I'll think about it.
