### ISSUE TITLE
Failed to find <insert ID0 here> in the SD dir.

### ISSUE THREAD

**Issue by DessertArbiter** [ihaveamac/ninfs#39]
Its giving me this error, i can see the folder and its the only one the 3DS recreates after i rename the Nintendo 3DS folder, so i know its correct

**Comment by ihaveamac** [comment]
The ID0 is based off the KeyY in movable.sed. If it can't find the right ID0, make sure you have the correct one (try re-dumping it?).

**Comment by DessertArbiter** [comment]
I got it, I was mounting the wrong directory, I thought it meant I was supposed to choose where it would be mounted on my PC, I didn't know I was supposed to choose the "Nintendo 3DS" folder
