### ISSUE TITLE
Install using pip fails

### ISSUE THREAD

**Issue by JoeJoeTV** [ihaveamac/ninfs#49]
I'm running Linux Mint 19.1 and I'm trying to install it with pip.
I have python 3 installed, but I had to install pip and setuptools manually.

If I now try to install it, it throws the following error:
`Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xujry9m3/ninfs/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-c3yqxr07-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-xujry9m3/ninfs/
`

**Comment by ihaveamac** [comment]
Is there more output than this? Where did you install pip from?

**Comment by jasonNodeX** [comment]
6 months later....
I had a similar error to this, it's possible you haven't installed the python3-dev packages:
**sudo apt-get install python3-dev
sudo apt-get install python3.6-dev
sudo apt-get install python3.X-dev** [x version of python 3]
