### ISSUE TITLE
Mount Switch partition directly

### ISSUE THREAD

**Issue by aedalzotto** [ihaveamac/ninfs#53]
Hello.

I have a partial backup of my Switch image, that have several files that represent the partitions (PRODINFO, SYSTEM, BCPKG, etc.).
Is it possible to mount only one of these partitions or i need to make a whole nand image to mount?

**Comment by ihaveamac** [comment]
Not at the moment, but it shouldn't be too difficult to support transparent encryption for a single partition.

**Comment by ihaveamac** [comment]
0b6fee18cd1fa023c324352c58978c5d4e0d9825 on the 2.0 branch adds this feature. Use with an argument like `--partition SYSTEM`. A single file will be in the mount with the decrypted partition.

**Comment by aedalzotto** [comment]
Awesome work.
Thanks.
