### ISSUE TITLE
Mismatch between essential/movable.bin and movable.sed got from godmode9

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [ihaveamac/ninfs#56]
Last 512 bits of essential/movable.bin are different from the dump made by godmode9, I suspect there is some error in how the fs is handled

**Comment by ihaveamac** [comment]
Is it different when you are reading movable.bin from essential.exefs in GodMode9?

**Comment by TanyaEleventhGoddess** [comment]
Sun, 19 Jan 2020 23:33:52 -0800 Ian Burgwin <notifications@github.com>:
> Is it different when you are reading movable.bin from essential.exefs in GodMode9?

No, it is the same (except for the fact that it's just movable and not movable.bin) but why are they different then?

**Comment by d0k3** [comment]
Is that a GM9 bug or is it a ninfs bug? You may have formated your 3DS in between?

**Comment by ihaveamac** [comment]
If GodMode9 shows the same contents, it's probably either a bug in the software that generated essential.exefs, or the system was formatted after generation which changes the key. Either way, this is most likely not an issue with ninfs.

**Comment by TanyaEleventhGoddess** [comment]
Mon, 20 Jan 2020 14:54:12 -0800 Ian Burgwin <notifications@github.com>:
> If GodMode9 shows the same contents, it's probably either a bug in the software that generated essential.exefs, or the system was formatted after generation which changes the key. Either way, this is most likely not an issue with ninfs.

Yes it was formatted. What key has been changed? That would be useful to know

**Comment by d0k3** [comment]
If you format it, the movable.sed and with it the SD crypto key changes. I think that solves it.
