### ISSUE TITLE
[LINUX][GUI][2.0] Gui module non functionnal also locks non-gui invocations

### ISSUE THREAD

**Issue by DistantThunder** [ihaveamac/ninfs#57]
Hi, 

Thank you for your work!

I tried to run the GUI version but came across this:

```
ninfs --help                                                             
Traceback (most recent call last):
  File "/home/darkeox/.local/bin/ninfs", line 11, in <module>
    load_entry_point('ninfs==2.0b1.dev0', 'console_scripts', 'ninfs')()
  File "/home/darkeox/.local/lib/python3.8/site-packages/ninfs/main.py", line 112, in gui
    import _gui
ModuleNotFoundError: No module named '_gui'
```

I don't know where this module is supposed to reside but it doesn't seem to lie within the package.

**Comment by ihaveamac** [comment]
2.0 lacks a gui right now. Use the master branch or a release if you want one. I’ll update the README soon to mention this.

**Comment by ihaveamac** [comment]
If you're trying to use individual mount types you should use them through separate commands like "mount_ncch" or "python3 -m ninfs ncch".

**Comment by ihaveamac** [comment]
This should hopefully not be an issue anymore now that 2.0 has a gui. Though I'm pretty sure I fixed this issue before anyway and forgot to close this.

**Comment by DistantThunder** [comment]
Thanks!
