### ISSUE TITLE
[Linux] Debian / Ubuntu Dependencies

### ISSUE THREAD

**Issue by nyuzu-nyuser** [ihaveamac/ninfs#59]
On Debian Testing / Bullseye and on Ubuntu 20.04 I found installing the following dependencies helped build and run it (unsure if all are used).

**System dependencies**

For building - edit, added libfuse2 reference below, but since it is a dependency for grub, odds are you already have it.

- `g++ python3-dev python3-setuptools python3-wheel`

    - opt_GUI: `g++ python3-dev python3-setuptools python3-wheel python3-tk

`apt install g++ python3-dev python3-setuptools python3-wheel`
-    - opt_GUI: `apt install g++ python3-dev python3-setuptools python3-wheel python3-tk`

As always make sure you are using python3, not 2 by running the commands as suggested:
`python3 -m pip`
or
`pip3`

Note that it says Setup -> Linux:

> Most distributions should have fuse enabled/installed by default. Use your package manager if it isn't. (Edit: this is libfuse, I found libfuse2 is installed on my Debian install)

~~However this is negated by the earlier,~~

> fusepy is pre-included until refuse has a fully stable release.

If you like to use a system copy, you can install python3-fusepy;

**Python dependencies** - I have no idea whether it is smarter to install via pip or the package maintainer version, but I typically prefer system repositories, trusting that pip may install another copy if there is a version mismatch

- `python3-fusepy`

-  `python3-pycryptodome`
    - Optional GUI: `python3-pyside2.qtcore`

`apt install python3-pyside2.qtcore python3-pycryptodome`

**Comment by nyuzu-nyuser** [comment]
I'd also advise linking to python's documentation on virtual environments, since you reference them,
https://packaging.python.org/tutorials/installing-packages/#creating-virtual-environments

**Comment by ihaveamac** [comment]
Just a few notes:

> Most distributions should have fuse enabled/installed by default. Use your package manager if it isn't.

This refers to [libfuse](https://github.com/libfuse/libfuse) directly (not fusepy which is a Python interface for it), though it's definitely not clear about that.

> fusepy is pre-included until refuse has a fully stable release.

The project only uses the included fusepy, not a system-provided or pip-provided one. It's like this because there are additions for Windows support to fusepy, but there's no release with them, and including dependencies that are not on PyPI is painful.

The others can be installed in any way.

**Comment by ihaveamac** [comment]
Anyway thanks for the issue, I'll get the README updated tomorrow for both 2.0 and master branches.

**Comment by ihaveamac** [comment]
Took a bit longer than "tomorrow" but the READMEs are updated now.
