### ISSUE TITLE
Getting error when trying to mount 3DS NAND Image.

### ISSUE THREAD

**Issue by TimmSkiller** [ihaveamac/ninfs#62]
The GUI shows up, I select my NAND Image file (.bin) and when I press "Mount", it gives me an error message "Failed to mount. Please check the output". In the output, this is what shows:
```
Cannot set WinFsp-FUSE file system mount point. 
The service python3.8 has failed to start (Status=c000000d)
```

This only happens when using directory mount. Using drive letter mount (for whatever reason) works. I also run the GUI in normal mode, as it gives me an error when trying to use it in admin mode.

**Comment by ihaveamac** [comment]
Can you show me the arguments it prints to the output when you try to run it?

**Comment by TimmSkiller** [comment]
`
ninfs v1.6.1 - https://github.com/ihaveamac/ninfs
Importing dependencies...
Loaded update config.
Setting up GUI...
Doing final setup...
UPDATE: Checking for updates... (Currently running v1.6.1)
Starting the GUI!
UPDATE: No new version. (Latest is v1.6.1)
-----------------------------------------------------------------------------------------------------------------------
Running: ['C:\\Users\\Kurdo Kadir\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\python.exe', 'C:\\Users\\Kurdo Kadir\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\ninfs', 'nandctr', '-f', 'C:/Users/Kurdo Kadir/Desktop/200528_CEM11357032_sysnand_000.bin', 'C:/Users/Kurdo Kadir/Desktop/asdf', '-r']
ninfs v1.6.1 - https://github.com/ihaveamac/ninfs
ncsd idx:0 fstype:1 crypttype:1 offset:00000000 size:0b100000 /twl_full.img
twl  idx:0                      offset:00012e00 size:08fb5200 /twln.img
twl  idx:1                      offset:09011a00 size:020b6600 /twlp.img
ncsd idx:1 fstype:4 crypttype:2 offset:0b100000 size:00030000 /agbsave.bin
ncsd idx:2 fstype:3 crypttype:2 offset:0b130000 size:00400000 /firm0.bin
ncsd idx:3 fstype:3 crypttype:2 offset:0b530000 size:00400000 /firm1.bin
ncsd idx:4 fstype:1 crypttype:2 offset:0b930000 size:2f5d0000 /ctrnand_full.img
ctr  idx:0                      offset:0b95ca00 size:2f3e3600 /ctrnand_fat.img
Cannot set WinFsp-FUSE file system mount point.
The service python3.8 has failed to start (Status=c000000d).
`

**Comment by ihaveamac** [comment]
Gonna guess that the MS Store version has limitations on what files it's allowed to access. Not sure how to fix this yet if I can.

**Comment by ihaveamac** [comment]
Confirmed to be an issue with the MS Store version of Python. I'm not sure what controls the permissions it has but for now, either use a drive letter mount (and copy files out for the NAND mount) or install from python.org or another source.
