### ISSUE TITLE
ninfs does not use specified seeddb.bin with --seeddb parameter

### ISSUE THREAD

**Issue by TimmSkiller** [ihaveamac/ninfs#65]
When I start ninfs in the command line and specify a valid path (I checked it) using --seeddb, it gives me this error when I try to mount a CIA that needs a seed: 
`Failed to mount /0000.00000000.ncch: InvalidNCCHError: ['C:\\Users\\User\\AppData\\Roaming\\3ds\\seeddb.bin', 'C:\\Users\\User\\.3ds\\seeddb.bin', 'C:\\Users\\User\\3ds\\seeddb.bin']`

`Failed to mount /0001.00000001.ncch: InvalidNCCHError: ['C:\\Users\\User\\AppData\\Roaming\\3ds\\seeddb.bin', 'C:\\Users\\User\\.3ds\\seeddb.bin', 'C:\\Users\\User\\3ds\\seeddb.bin']`.

These are the parameters I used to run it: `.\ninfs.exe cia --seeddb .\seeddb.bin --boot9  .\boot9.bin "C:\Users\User\Downloads\Runbow Pocket (USA).cia" Z:`
But having the seeddb.bin file in AppData\Roaming\3ds works.

**Comment by ihaveamac** [comment]
This was already fixed on the 2.0 branch by rewriting how seeds are handled.
