### ISSUE TITLE
Cannot mount Super Smash Bros. Special Demo Version (eShop Demo)

### ISSUE THREAD

**Issue by LolHacksRule** [ihaveamac/ninfs#69]
When I try to mount Super Smash Bros. Special eShop demo (USA) as a decrypted 3DS file (MD5: 8E18F555182E42B524DBA8A6FC9C5462), I always get this error.

> Failed to mount ExeFS: InvalidExeFSError: Failed to convert name, probably not a valid ExeFS
> Failed to mount RomFS: InvalidRomFSHeaderError: Length in RomFS Lv3 header is not 0x28

Other archive viewing software like Toolbox opens it fine. Any advice?

**Comment by ihaveamac** [comment]
Does GodMode9 handle it correctly? My first thought is that the crypto flags in the NCCH header were not fixed, which happens when using legacy (i.e. ancient) decrypt tools.

**Comment by LolHacksRule** [comment]
It probably should, testing rn

**Comment by LolHacksRule** [comment]
GM9 outputs 

> invalid directory object

when trying to navigate to exefs or romfs directory.
