### ISSUE TITLE
No boot9/etc. file created on mac

### ISSUE THREAD

**Issue by RikerW** [ihaveamac/ninfs#74]
Installed via `python3 -mpip install ninfs==2.0a3`, launched with `ninfs` in Terminal. Seems to load up fine - but there's no folder named `.3ds` in either `~/` or `/`, and I don't see it in the module files in `/usr/local/lib/whatever` either. Not sure what's up, it's probably just somewhere I'm not expecting. 

Distro: OS X 10.14.6
Python: Python 3.9.1
Ninfs: ninfs v2.0a3 on Python 3.9.1

**Comment by ihaveamac** [comment]
You're supposed to create this directory and put boot9 and seeddb in it.

**Comment by RikerW** [comment]
What are the contents of boot9 or seeddb? It mentioned something like that on the gbatemp tutorial but there's no file to "fix boot9". I'm brand new to 3ds emulating or anything like that, sorry if this is a dumb question.

**Comment by ihaveamac** [comment]
boot9 can be dumped with: https://ihaveamac.github.io/dump.html

seeddb: https://github.com/ihaveamac/3DS-rom-tools/wiki/SeedDB-list

**Comment by ihaveamac** [comment]
Both have encryption keys. boot9 has shared keys, seeddb is for digital games released after around early-2015.

**Comment by RikerW** [comment]
Thank you!
