### ISSUE TITLE
ninfs failed to «AttachConsole(6500)»

### ISSUE THREAD

**Issue by ihaveawindows** [ihaveamac/ninfs#80]
I was going to extract FE:E Shadows of Valentia to get the romfs folder, but I get this error.
Log file:
[ninfs-error_2021-05-06_19-45-45.log](https://github.com/ihaveamac/ninfs/files/6434540/ninfs-error_2021-05-06_19-45-45.log)
What is wrong with it? Is it a bug? Or maybe there's something wrong with my end?
Thanks in advance

**Comment by ihaveamac** [comment]
Weird since this error should not cause an exit. Return code being 0 also means it exited without issue. How did you run ninfs?

**Comment by ihaveawindows** [comment]
i ran ninfs using ninfsw

**Comment by ihaveamac** [comment]
Did it fail immediately? Are you able to use other mount types?

**Comment by ihaveawindows** [comment]
a. No
b. No, I havent tested it with other mount types, I've only used NCCH mount types

**Comment by ihaveamac** [comment]
> What do you mean by fail immediately? When I open the program or when I try to mount?

When the mount is being created, does it fail at that point, or some time after that?

**Comment by ihaveawindows** [comment]
> > What do you mean by fail immediately? When I open the program or when I try to mount?
> 
> When the mount is being created, does it fail at that point, or some time after that?

Some time after that, sorry for late respond
