### ISSUE TITLE
2.0a6 not listed on pip

### ISSUE THREAD

**Issue by tsidaa** [ihaveamac/ninfs#85]
`ERROR: Could not find a version that satisfies the requirement ninfs==2.0a6 (from versions: 1.4, 1.5, 1.6, 1.6.1, 2.0a1, 2.0a2, 2.0a3, 2.0a4, 2.0a5)
ERROR: No matching distribution found for ninfs==2.0a6`

Not listed here either: https://pypi.org/project/ninfs/#history

**Comment by ihaveamac** [comment]
Oops, forgot to upload it. It's there now: https://pypi.org/project/ninfs/2.0a6/
